[package]
name = "wknd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4"
rand = "^0"
pbr = "^1"
ordered-float = "^2"
rayon = "^1"
image = "*"
